language: android
android:
    components:
        - build-tools-19.1.0
        - android-19
        - extra-google-google_play_services
        - addon-google_apis-google-19
    licences:
        - '.+'

before_script:
        - android list target
        - mkdir libsrc
        - cp -r /usr/local/android-sdk/extras/google/google_play_services/libproject/google-play-services_lib libsrc/
        - ls libsrc/google-play-services_lib
        - android update lib-project -p libsrc/google-play-services_lib -t android-19
        - echo setup emulator
        - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:19"
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &

script:
        - cd test/stacklr_test
        - ant debug install clear test
