language: android
android:
    components:
        - build-tools-23.0.1
        - android-19
        - extra-google-google_play_services
        - addon-google_apis-google-19
        - extra-android-support
        - extra-android-m2repository
    licences:
        - '.+'

#before_script:
#        - android list target
#        - mkdir libsrc
#        - echo setup emulator
#        - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:19"
#        - emulator -avd test -no-skin -no-audio -no-window &
#        - android-wait-for-emulator
#        - adb shell input keyevent 82 &

#script:
#        - cd test/stacklr_test
#        - ant debug install clear test

script:
        - ./gradlew build