language: android
android:
    components:
        - build-tools-19.1.0
        - android-16
        - extra-google-google_play_services
    licences:
        - '.+'

before_script:
        - mkdir libsrc
        - cp -r /usr/local/android-sdk/extras/google/google_play_services/libproject/google-play-services_lib libsrc/
        - android update lib-project -p libsrc/google-play-services_lib -t android-16
